[package]
name = "cdk-sqlite"
version = "0.1.0"
edition = "2021"
license.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["mint", "wallet"]
mint = ["cdk/mint"]
wallet = ["cdk/wallet"]
nostr = ["cdk/nostr"]

[dependencies]
bitcoin.workspace = true
const_format = "0.2.32"
sqlx = { version = "0.6.3", default-features = false, features = ["runtime-tokio-rustls", "chrono", "sqlite"] }
cdk = { workspace = true, default-features = false }
thiserror.workspace = true
tokio = { workspace = true, features = [
    "time",
    "macros",
    "sync",
] }
tracing.workspace = true
async-trait.workspace = true
serde_json.workspace = true
